// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2P.Server.Data;

#nullable disable

namespace P2P.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260820121630_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("P2P.Server.Data.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT")
                        .HasColumnName("detail");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event");

                    b.Property<string>("Ts")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ts");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Ts")
                        .HasDatabaseName("idx_audit_ts");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("P2P.Server.Data.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ClientVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("client_version");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("device_name");

                    b.Property<byte[]>("DeviceSecret")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("device_secret");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("disabled");

                    b.Property<string>("LastSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("MacCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mac_code");

                    b.Property<string>("Os")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("os");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("RemoteCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_code");

                    b.Property<byte[]>("StaticPubKey")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("static_pub_key");

                    b.Property<string>("VirtualIp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("virtual_ip");

                    b.HasKey("Id");

                    b.HasIndex("MacCode")
                        .HasDatabaseName("idx_devices_mac");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("idx_devices_owner");

                    b.HasIndex("RemoteCode")
                        .IsUnique();

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("P2P.Server.Data.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("InviteCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("invite_code");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_default");

                    b.Property<string>("JoinPolicy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("join_policy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_user_id");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("OwnerUserId");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("P2P.Server.Data.GroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Approved")
                        .HasColumnType("INTEGER")
                        .HasColumnName("approved");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<string>("JoinedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("joined_at");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("idx_gm_device");

                    b.HasIndex("GroupId", "DeviceId")
                        .IsUnique();

                    b.ToTable("group_members", (string)null);
                });

            modelBuilder.Entity("P2P.Server.Data.JoinRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<string>("HandledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("handled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("GroupId");

                    b.ToTable("join_requests", (string)null);
                });

            modelBuilder.Entity("P2P.Server.Data.LanSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Cidr")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cidr");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("device_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Cidr")
                        .IsUnique();

                    b.ToTable("lan_segments", (string)null);
                });

            modelBuilder.Entity("P2P.Server.Data.Mapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<int>("LocalPort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("local_port");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerDeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_device_id");

                    b.Property<string>("Proto")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("proto");

                    b.Property<string>("TargetAddr")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_addr");

                    b.Property<Guid>("TargetDeviceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_device_id");

                    b.Property<int>("TargetPort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_port");

                    b.HasKey("Id");

                    b.HasIndex("TargetDeviceId")
                        .HasDatabaseName("idx_mappings_target");

                    b.HasIndex("OwnerDeviceId", "LocalPort", "Proto")
                        .IsUnique();

                    b.ToTable("mappings", (string)null);
                });

            modelBuilder.Entity("P2P.Server.Data.MappingStat", b =>
                {
                    b.Property<Guid>("MappingId")
                        .HasColumnType("TEXT")
                        .HasColumnName("mapping_id");

                    b.Property<long>("BytesDown")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bytes_down");

                    b.Property<long>("BytesUp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bytes_up");

                    b.Property<long>("RelayBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("relay_bytes");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("MappingId");

                    b.ToTable("mapping_stats", (string)null);
                });

            modelBuilder.Entity("P2P.Server.Data.PunchStat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<int>("Concurrency")
                        .HasColumnType("INTEGER")
                        .HasColumnName("concurrency");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<Guid>("InitiatorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("initiator_id");

                    b.Property<string>("Proto")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("proto");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("result");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_id");

                    b.Property<string>("Ts")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ts");

                    b.HasKey("Id");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("TargetId");

                    b.HasIndex("Ts")
                        .HasDatabaseName("idx_punch_ts");

                    b.ToTable("punch_stats", (string)null);
                });

            modelBuilder.Entity("P2P.Server.Data.ServerConfigEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("server_config", (string)null);
                });

            modelBuilder.Entity("P2P.Server.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("disabled");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_admin");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("P2P.Server.Data.Device", b =>
                {
                    b.HasOne("P2P.Server.Data.User", "Owner")
                        .WithMany("OwnedDevices")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("P2P.Server.Data.Group", b =>
                {
                    b.HasOne("P2P.Server.Data.User", "Owner")
                        .WithMany("OwnedGroups")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("P2P.Server.Data.GroupMember", b =>
                {
                    b.HasOne("P2P.Server.Data.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P2P.Server.Data.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("P2P.Server.Data.JoinRequest", b =>
                {
                    b.HasOne("P2P.Server.Data.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P2P.Server.Data.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("P2P.Server.Data.LanSegment", b =>
                {
                    b.HasOne("P2P.Server.Data.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("P2P.Server.Data.MappingStat", b =>
                {
                    b.HasOne("P2P.Server.Data.Mapping", "Mapping")
                        .WithOne("Stats")
                        .HasForeignKey("P2P.Server.Data.MappingStat", "MappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mapping");
                });

            modelBuilder.Entity("P2P.Server.Data.PunchStat", b =>
                {
                    b.HasOne("P2P.Server.Data.Device", null)
                        .WithMany()
                        .HasForeignKey("InitiatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("P2P.Server.Data.Device", null)
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("P2P.Server.Data.Mapping", b =>
                {
                    b.Navigation("Stats");
                });

            modelBuilder.Entity("P2P.Server.Data.User", b =>
                {
                    b.Navigation("OwnedDevices");

                    b.Navigation("OwnedGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
