// 本文件由 export-ts 反射生成（06 §5、08 §2③），禁止手改；
// 源：LocalWebApi 真实路由表（src/Tools/ExportTs @ 2026-10-01T11:42:33Z）。前端禁止手写 API 字符串路径。

export const ApiPaths = {
  AuthChangePassword: "/api/auth/change-password",
  AuthLogin: "/api/auth/login",
  AuthLogout: "/api/auth/logout",
  AuthMe: "/api/auth/me",
  AuthRegister: "/api/auth/register",
  Device: "/api/device",
  DeviceResetRemoteCode: "/api/device/reset-remote-code",
  Devices: "/api/devices",
  Diagnostics: "/api/diagnostics",
  GroupRequestsByIdApprove: "/api/group-requests/{id}/approve",
  GroupRequestsByIdReject: "/api/group-requests/{id}/reject",
  Groups: "/api/groups",
  GroupsJoin: "/api/groups/join",
  GroupsById: "/api/groups/{id}",
  GroupsByIdInvite: "/api/groups/{id}/invite",
  GroupsByIdLeave: "/api/groups/{id}/leave",
  GroupsByIdMembersByDeviceidKick: "/api/groups/{id}/members/{deviceId}/kick",
  GroupsByIdRequests: "/api/groups/{id}/requests",
  LanSegments: "/api/lan-segments",
  LanSegmentsById: "/api/lan-segments/{id}",
  Logs: "/api/logs",
  LogsExport: "/api/logs/export",
  Mappings: "/api/mappings",
  MappingsById: "/api/mappings/{id}",
  MappingsByIdDisable: "/api/mappings/{id}/disable",
  MappingsByIdEnable: "/api/mappings/{id}/enable",
  MappingsByIdRetry: "/api/mappings/{id}/retry",
  PeersByDeviceid: "/api/peers/{deviceId}",
  Settings: "/api/settings",
  SystemState: "/api/system/state",
  UpgradeInfo: "/api/upgrade/info",
  WizardRegister: "/api/wizard/register",
  WizardResult: "/api/wizard/result",
  WizardServerTest: "/api/wizard/server-test",
  WsStatus: "/ws/status",
} as const;

export type ApiPath = (typeof ApiPaths)[keyof typeof ApiPaths];

/** 端点元数据（method×path；WS 路由 methods 为 ["WS"]）。 */
export const ApiEndpoints = [
  { path: "/api/auth/change-password", methods: ["POST"] },
  { path: "/api/auth/login", methods: ["POST"] },
  { path: "/api/auth/logout", methods: ["POST"] },
  { path: "/api/auth/me", methods: ["GET"] },
  { path: "/api/auth/register", methods: ["POST"] },
  { path: "/api/device", methods: ["GET"] },
  { path: "/api/device", methods: ["PUT"] },
  { path: "/api/device/reset-remote-code", methods: ["POST"] },
  { path: "/api/devices", methods: ["GET"] },
  { path: "/api/diagnostics", methods: ["GET"] },
  { path: "/api/group-requests/{id}/approve", methods: ["POST"] },
  { path: "/api/group-requests/{id}/reject", methods: ["POST"] },
  { path: "/api/groups", methods: ["GET"] },
  { path: "/api/groups", methods: ["POST"] },
  { path: "/api/groups/join", methods: ["POST"] },
  { path: "/api/groups/{id}", methods: ["PUT"] },
  { path: "/api/groups/{id}", methods: ["DELETE"] },
  { path: "/api/groups/{id}/invite", methods: ["GET"] },
  { path: "/api/groups/{id}/invite", methods: ["DELETE"] },
  { path: "/api/groups/{id}/leave", methods: ["POST"] },
  { path: "/api/groups/{id}/members/{deviceId}/kick", methods: ["POST"] },
  { path: "/api/groups/{id}/requests", methods: ["GET"] },
  { path: "/api/lan-segments", methods: ["GET"] },
  { path: "/api/lan-segments", methods: ["POST"] },
  { path: "/api/lan-segments/{id}", methods: ["DELETE"] },
  { path: "/api/logs", methods: ["GET"] },
  { path: "/api/logs/export", methods: ["GET"] },
  { path: "/api/mappings", methods: ["GET"] },
  { path: "/api/mappings", methods: ["POST"] },
  { path: "/api/mappings/{id}", methods: ["PUT"] },
  { path: "/api/mappings/{id}", methods: ["DELETE"] },
  { path: "/api/mappings/{id}/disable", methods: ["POST"] },
  { path: "/api/mappings/{id}/enable", methods: ["POST"] },
  { path: "/api/mappings/{id}/retry", methods: ["POST"] },
  { path: "/api/peers/{deviceId}", methods: ["GET"] },
  { path: "/api/peers/{deviceId}", methods: ["PUT"] },
  { path: "/api/settings", methods: ["GET"] },
  { path: "/api/settings", methods: ["PUT"] },
  { path: "/api/system/state", methods: ["GET"] },
  { path: "/api/upgrade/info", methods: ["GET"] },
  { path: "/api/wizard/register", methods: ["POST"] },
  { path: "/api/wizard/result", methods: ["GET"] },
  { path: "/api/wizard/server-test", methods: ["POST"] },
  { path: "/ws/status", methods: ["WS"] },
] as const;
